イベント作成API
tetsu-777/rakuraku-reserve-app pull request #13
Opened 2024-01-23 13:50 UTC by tetsu-777

# 機能詳細
- イベント作成用のAPIを実装
[POST] http://localhost:8080/api/events/
```
{
    "title": "test",
    "body": "test",
    "eventDate": "2022-01-23T15:04:05Z",
    "joinDeadlineDate": "2022-01-23T15:04:05Z",
    "capacity": "50"
}
```
- バリデーションチェックの実装
title : 必須、256文字以内
eventDate, joinDeadlineDate : timestamp(ex. 2022-01-23T15:04:05Z)
capacity : 0~1000
# 実装確認
- 正常系
<img width="615" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/131426881/9b7c4725-9428-4c37-8700-573503b06dd6">

- 異常系１（title, capacity バリデーションエラー）
<img width="579" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/131426881/1e41c618-9483-4f12-af86-6218864df3cd">

- 異常系２（eventDate）
<img width="583" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/131426881/444d2299-e5b7-4ed7-9246-6fd0b379be02">

# 共有事項
- 特になし

2024-02-04 05:36 UTC, Rin0107 commented on app/controller/eventController.go
ファイル命名規則がスネークケースなら統一すること！

2024-02-04 06:33 UTC, Rin0107 requested changes
ファイル名・コメントを確認して修正して下さい！

2024-02-04 06:33 UTC, Rin0107 commented on app/service/eventService.go
> +	eventDate, err := time.Parse(time.RFC3339, eventDateStr)
リクエストの日にちってTZ指定で送るんじゃなくて、文字列で送れた方がフロントから送るのが楽な気がする！
ただ、dart, flutterで送るときに逆にUTCで送る方が楽な可能性はあるから、そっちの仕様に合わせるってことで頭の片隅においておいて！

2024-02-04 06:34 UTC, Rin0107 commented
【お願い】
実装確認のときに、例になるリクエストはjson形式で書いておいてほしい！
確認のときに楽だから笑

あと、フロントとはAPI通信（おそらくjson形式）でやり取りすると思うから、jsonでリクエストを投げてテストしたい！

2024-02-05 12:00 UTC, tetsu-777 reviewed
リクエストデータについて
json形式で書いておいたけど、
ＰＯＳＴＭＡＮでテストする時、
form-dataからリクエストデータを送らないとエラーになっちゃう。
おそらくjsonをデコード（Unmarshal）する必要があるのかな？
詰まって時間かかりそうだから、違う実装から進めていこうかな？

2024-02-05 12:00 UTC, tetsu-777 commented on app/service/eventService.go
> +	eventDate, err := time.Parse(time.RFC3339, eventDateStr)
確認

2024-02-05 13:56 UTC, kazuoikeda1411 commented
> リクエストデータについて json形式で書いておいたけど、 ＰＯＳＴＭＡＮでテストする時、 form-dataからリクエストデータを送らないとエラーになっちゃう。 おそらくjsonをデコード（Unmarshal）する必要があるのかな？ 詰まって時間かかりそうだから、違う実装から進めていこうかな？

自分はリクエストのstructを別でコントローラーに持たせて`json:"password" validate:"required"`とかで設定したらいけた！
flutterとの通信が基本非同期通信形式になっているからできるだけJSONで通信した方がいいなとは思うけど、form形式でも確か通信はできるはず。。。

ご参考までに🙇

2024-02-06 15:05 UTC, Rin0107 approved these changes

2024-02-06 15:07 UTC, Rin0107 commented
日にちのやり取りがUTCで良いか、文字列とかの方が良いか、flutterの実装のときに再度確認してね！
LGTM!

2024-02-08 13:13 UTC, merged