ユーザー詳細取得の実装
tetsu-777/rakuraku-reserve-app pull request #27
Opened 2024-02-08 13:15 UTC by kazuoikeda1411

# 機能詳細
- ユーザー情報を取得する
- パスは２種類だが、実際の処理内容は同一
  - 管理者権限でuserIdを指定してユーザー情報を取得する
  - ログイン状態で、セッションIDをもとに自身のユーザー情報を取得する
- 取得する情報は以下の通り
  - name
  - email
  - userIcon
  - role
  - created_at
  - updated_at

# 実装確認
### 管理者権限でuserIdを指定してユーザー情報を取得する
> 管理者権限でログインしてください
- ユーザーが存在して成功するとき
  - GETで`http://localhost:8080/api/admin/user/1`
<img width="627" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/881a45a4-5e78-4535-bdda-af85232581d5">

- ユーザーが存在しなくて失敗するとき
  - GETで`http://localhost:8080/api/admin/user/100`
<img width="634" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/6e528b7e-ca27-4ae4-af74-4e8290d2edf3">

### ログイン状態で、セッションIDをもとに自身のユーザー情報を取得する
> ログインしてください（管理者でもユーザーでも同様の処理になります）
> ログインさ入れていないと認可機能が働きます
- 成功時
  - GETで`http://localhost:8080/api/user` 
<img width="645" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/dca02154-3bf9-4b3a-b5f3-25277f72dbcc">

# 共有事項
- ユーザー登録をしていなければ先にユーザー、管理者権限のユーザーを作成してください
- 本実装には認可機能を実装しています

2024-02-13 13:04 UTC, Rin0107 requested changes
実装はいい感じ！

ただ、この機能って何を目的として実装したもの？（スプシで言う何の機能？）
というのも、もしもユーザーがこの機能を使うんだとしたら、少なくともroleの情報は渡さないほうが良いなと思って！

教えて下さい！

2024-02-13 22:28 UTC, kazuoikeda1411 commented
スプシでいうユーザー詳細画面機能かな。
管理者がユーザー一覧からユーザー詳細画面に飛ぶ時とか、ユーザーがマイページ（実装するかわからんけど）に遷移するときに必要になるかなと考えてる。
> まだユーザー情報少ないけど、ユーザー紹介文とか仕様が増えたときにデータ増やすだけでいろんなところでこの処理使えるようにしたいなというふうに思ってる、、、
画面で権限によって処理変えたい時とかあるかなと思ってroleは残しておいた感じです。

2024-02-14 03:29 UTC, kazuoikeda1411 commented
ロールについて取得できないように変更しました。
> 値を入れないように対応しました。（取得したUserそのままレスポンスしているので項目に上がってるけど、、、）

```
{
    "UserId": 1,
    "Name": "hoge",
    "Email": "john@example.com",
    "Password": "",
    "UserIcon": "icon",
    "Role": "",
    "PasswordResetToken": "",
    "CreatedAt": "2024-02-04T03:41:27.877044Z",
    "UpdatedAt": "2024-02-11T08:24:05.617332Z",
    "DeletedAt": null
}
```

2024-02-14 14:29 UTC, Rin0107 approved these changes

2024-02-14 14:29 UTC, Rin0107 commented
なるほどね～
ほんとなら
`"Role": "",`
の部分入れたくないけど、
`User struct`は持っちゃってるもんね～

（更にほんとを言えば、管理機能は別アプリケーションで持たせたいかもね～。管理者権限を含むRoleの情報があると、Roleの制御のときに管理者権限でアクセスできないように気をつけんといかんから。）（別アプリケーションを作るのはコストがすごいからあんまりやらん気がするけど）

一旦今の修正のままにしてもらって、もし今後の開発でRole情報が必要なら修正して渡せるようにしようか！
LGTM！

2024-02-14 21:58 UTC, merged