ユーザー削除処理の実装
tetsu-777/rakuraku-reserve-app pull request #30
Opened 2024-02-10 05:04 UTC by kazuoikeda1411

# 機能詳細
- ユーザーを削除する処理
- 削除処理は理論削除（データは残っている、deleted_atに日付を入れる）
- ログイン（管理者）していることが前提
- ユーザーIDをパラムに入れてリクエストする
- 自分自身は削除できないようにしている
- 存在するユーザーを削除、存在するか先に確認する
> 存在しなかった場合500を返す（リクエストで存在するユーザーを特定させないように）

# 実装確認
- 削除成功時
  - 管理者でログイン
  - DELETEで`api/admin/user/delete/:userId`
  > 必要に応じて削除するユーザーを登録してください
<img width="646" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/525d88d9-afeb-4479-911f-a5ccb3631c1a">

- 削除失敗時（ユーザーが存在しない場合）
  - 成功時と同じリクエストをもう一度送る
<img width="704" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/05633f6f-13ad-4740-8db1-a7d0acf1086d">
<img width="961" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/30ff2b80-d977-4514-8ea4-89c4aa482b1a">

- 削除失敗時（自信を削除しようとするとき）
  - ログインしているユーザーIDを調べておく（GETで`http://localhost:8080/api/admin/users`で確認しておく）
  - 調べたユーザーIDでDELETEで`api/admin/user/delete/:userId`
<img width="627" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/6060aa95-644f-4c96-919c-32e628787afe">
<img width="976" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/d80acc7d-c680-4469-b140-499c1adc52e3">

# 共有事項
- ユーザー登録で一度登録されているメールアドレスは登録できないようになっている仕様について検討が必要かと思われる

2024-02-13 13:26 UTC, Rin0107 requested changes
実装は全体的にいい感じ！

強いて言うなら、ユーザーの削除に失敗したときのレスポンスステータスコードは500じゃ無い方がいいかな！

ユーザーに不要な情報を提供しないっていう考えは良い！
> 存在しなかった場合500を返す（リクエストで存在するユーザーを特定させないように）


けど、500を返すと
- むしろ変な情報をユーザーに提供してしまう
- 開発時のデバッグで誤解してしまう（開発者目線で500は絶対に直さないといけないエラーなため）

この場合は[403 Forbidden](https://developer.mozilla.org/ja/docs/Web/HTTP/Status/403)とかが良いかも！

あるいはめんどくさいときは[404 Not Found](https://developer.mozilla.org/ja/docs/Web/HTTP/Status/404)にしちゃうかもね！
> サーバーは認証されていないクライアントからリソースの存在を隠すために、 403 の代わりにこのレスポンスを返すことがあります。

2024-02-14 03:20 UTC, kazuoikeda1411 commented
存在しないユーザー、自身のユーザーを削除しようとしたとき403を返す処理に変更しました。
DELETEで`api/admin/user/delete/100`
<img width="633" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/5861134c-6b36-47a1-b3d3-f426e43858f6">
> `api/admin/user/delete/:userId`でログインユーザーのidを指定しても上記と同様のレスポンスが返ります

確認お願いします！

2024-02-14 14:31 UTC, Rin0107 commented
LGTM!

2024-02-14 14:32 UTC, Rin0107 approved these changes

2024-02-14 21:59 UTC, merged