ユーザー情報変更処理の実装
tetsu-777/rakuraku-reserve-app pull request #33
Opened 2024-02-13 22:16 UTC by kazuoikeda1411

# 機能詳細
- ユーザー情報を変更する処理
- 権限によって処理を分けようと思っている
  - 管理者：どのユーザーの情報も変更ができるようにする
    - name
    - email
    > 他のユーザーのメールも変更できるように設定
    - userIcon
    - role
  - ユーザー：自分の情報のみを変更
    - name
    - email
    - userIcon
    > ユーザー権限の場合、更新するときにroleをuserとして変更処理している
- リクエストボディに以下を入れる
  - name
  - email（変更して問題ない？）
  - userIcon
  - role（管理者のみ、ユーザーが入れたら無視される）
- リクエストパラムにユーザーIDを入れる

# 実装確認
- 成功時（userId3のhogeユーザーを作る、ユーザー権限、作ったユーザーでログインする）
  - PATCHで`http://localhost:8080/api/user/3`
```
{
    "name":"hoge",
    "email":"hoge@example.com",
    "user_icon":"icon",
    "role":"user"
}
```
<img width="628" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/1cb87df1-c22b-4da1-814a-bbbcc51d640c">
  - 自分のメールアドレスで登録（上記と同様のリクエスト）
<img width="649" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/78dbba2c-9260-40b7-a457-c97c768bcd9f">
  - 自分のメール以外が指定されたとき、重複したメールがあるか確認する（変更のユーザーのemailは設定可能にする）
    - `http://localhost:8080/api/user/3`
```
{
    "name":"hoge",
    "email":"hoge1@example.com",
    "user_icon":"icon",
    "role":"user"
}
```
<img width="641" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/cca5cd89-de82-40b3-bd7d-302af19e7635">

- 失敗時
  - user権限の時、自身のuserIdではない値をパラムに入れた時
    - http://localhost:8080/api/user/1
    > ボディは変えず自身以外のuserIdを指定する
<img width="660" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/59775305-e361-44fc-82bf-b050fab81c16">

  - 存在しないuserIdが指定された時500を返す（管理者でログインしておく）
    - `http://localhost:8080/api/user/300`
    > ボディは同じ
<img width="664" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/70d9514d-a87c-41ac-b0d0-e14fe708291f">

- バリデーション時
  - `http://localhost:8080/api/user/3`
```
{
    "name":"",
    "email":"hoge1@example.com",
    "user_icon":"icon",
    "role":"user"
}
```
<img width="646" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/ad2a9aff-2272-42ff-a6d8-edb59770aacc">

# 共有事項
- アイコンについては画像の取り扱いについて相談が必要と判断し、現在は文字列での保存にしている。
- 後でIssueに入れておきます。
- 削除したメールアドレスの指定については別Issueで対応します

2024-02-14 03:43 UTC, kazuoikeda1411 commented
以下Issueあげました。
[アイコン画像について](https://github.com/tetsu-777/rakuraku-reserve-app/issues/34)

2024-02-14 15:24 UTC, Rin0107 requested changes
【修正依頼】
お願いします！

あと、確認・調整依頼を１つ！メンバーの間で基本の考え方を共有してほしい！

2024-02-15 22:12 UTC, kazuoikeda1411 commented on app/controller/user_controller.go
> +		if !service.IsEmail(userInformationToUpdate.Email) {
論理削除しててDBに情報としては残ってる（emailカラムはユニーク）から今のところはそれに則って編集処理の除外項目として残してる。。。

別Issueで対応します、、、
すんません🙇

2024-02-15 22:20 UTC, kazuoikeda1411 commented on app/controller/user_controller.go
> +	message := ResponseMessage{Message: "ユーザー情報が変更されました"}
自分としては今のところはメッセージだけでいいのかなと考えてる
（メリットにある通り不要な情報を渡さない方がいいなと思うし）
フロント側の変更時の処理実装するときに変更処理のレスポンスに情報欲しいなと思ったら変えればいいしなと考えてる。。。（よりシンプルに実装ができたらな〜て感じ）

> ミニマムに実装してこれからどんどん変更していくと考えると、データ取得と変更処理は別で処理しておいた方が、それぞれの実装の可用性高いかなと考えてメッセージにしたいなと考えてる

2024-02-15 22:26 UTC, kazuoikeda1411 commented
以下２点修正しました
- role情報をそもそも変更できないようリクエスト情報、DB変更処理に乗せないように処理修正
- user権限の時に自身以外のuserIdを指定した時・指定したuserIdが存在しない場合403を返すようにする
![image](https://github.com/tetsu-777/rakuraku-reserve-app/assets/118358124/a1db6867-1c03-40bf-a523-cb27b02a2dec)
> 上記はuserIdが存在しない場合のリクエスト送った時）
> PATCHで`http://localhost:8080/api/user/30`

確認お願いします🙇
調整については後でDiscord投げとく！

2024-02-15 22:41 UTC, Rin0107 approved these changes

2024-02-15 22:42 UTC, Rin0107 commented
LGTM!

2024-02-16 03:19 UTC, merged