24 reserve equipment
tetsu-777/rakuraku-reserve-app pull request #35
Opened 2024-02-14 11:20 UTC by tetsu-777

# 機能詳細
- 新規機材予約をDBに挿入する処理
- パラメータに含まれているequipmentIdとRequestデータを使用して挿入。
- Requestデータの形は以下の通り
{
    "userId": 1,
    "reservationStartTime": "2022-01-23T15:00:00Z",
    "reservationEndTime": "2022-01-23T18:00:00Z",
    "activityStartTime": "2022-01-23T15:00:00Z",
    "activityEndTime": "2022-01-23T17:00:00Z"
}
# 実装確認
- 挿入成功時
<img width="868" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/131426881/9c04b46c-79a7-480c-bdf0-b564ca683526">
- 挿入失敗時（指定のequipmentIdが無い）
<img width="890" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/131426881/2c52c3a9-bf88-41f7-9db2-d136ae63e5ef">
- 挿入失敗時（reservationStartTimeが無い）
<img width="877" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/131426881/53f2d982-fcb8-4c70-9570-824eee63fa6b">

# 共有事項
- app/database/init/init_database.sqlの変更
    - equipment_reservationsテーブルにとりあえずreport_idを持たせない方向で修正した。

2024-02-14 13:02 UTC, kazuoikeda1411 requested changes
コメントしました！
いくつか修正対応とどんな感じで考えてたのかなっての聞きたいなと思ってコメント入れてます🙇

確認お願いします！

2024-02-14 13:15 UTC, tetsu-777 commented on app/controller/equipment_controller.go
> +	"fmt"
それは意図しない形で残ってた、削除します

2024-02-14 13:27 UTC, tetsu-777 commented on app/controller/equipment_controller.go
> +	var equipmentReservingRequest model.EquipmentReservingRequest
modelにリクエスト用のstructを定義した理由は2つあって、
1. controllerに書くと分量が重くなる（fat controllerはコードが見にくくなるかなと、主観だけど）から、controller△
2. リクエスト用のstructをcontrollerでもserviceでも使用したくて、serviceに持たせるとcontroller⇔serviceでimportし合うことになって、エラー起きちゃうから、serviceは×

でも、確かにバリデーションをどこでやるか考えが曖昧なところがあった。

2024-02-14 13:28 UTC, tetsu-777 commented on app/controller/equipment_controller.go
> +	c.IndentedJSON(404, gin.H{"error": err.Error()})
確かに統一感ないな、修正します！

2024-02-14 13:37 UTC, tetsu-777 commented on app/service/equipment_service.go
> +		return err
都度errに値が入っているときに返すようにしていたから、良いのかな～と思ってた！
メモリくっちゃうの？

2024-02-14 13:38 UTC, tetsu-777 commented on app/database/init/init_database.sql
> +    -- report_id SERIAL,
🙇‍♂️

2024-02-14 13:39 UTC, tetsu-777 commented on app/model/equipment.go
> +	}
納得！修正します！

2024-02-14 13:46 UTC, tetsu-777 commented on app/model/equipment.go
> +	}
<img width="882" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/131426881/628048ac-cf96-47b3-80ac-41aca1c3fc48">
レスポンスはこんな感じにしてみた！

2024-02-15 03:20 UTC, kazuoikeda1411 commented on app/controller/equipment_controller.go
> +	var equipmentReservingRequest model.EquipmentReservingRequest
テストする前提の話になるけどmodelはできればDB接続に関連した処理に注力した方がいいなって思った。
chatgtpに聞いてみたら以下の感じだって（これはコントローラ付近にロジックがあった方がいい感じかな）
> 一般的には、バリデーションはデータの入力元に最も近い箇所で行うことが重要です。

妥協案としてはリクエストクラスを別パッケージで作ってそこにバリデーション処理を描いちゃうとかかな？
実装適応させるのめんどくさそうだけど、、、

2024-02-15 03:25 UTC, kazuoikeda1411 commented on app/service/equipment_service.go
> +		return err
goはガベージコレクション標準適応されてる感じらしいけど、javaとかだと変数が複数参照とか挿入されてるとメモリに残りやすくなるのがあって、、、

メモリリークとかが起こったら対処する感じにしようか〜
ここ修正不要で！
（以下メモリ管理について気をつける感じの話載せとく！）
```
例えば、スライスやマップに同じデータが複数回追加される場合、そのデータに対する参照が増え、解放されない可能性があります。また、循環参照が発生した場合も、メモリが解放されない可能性があります。

これらの問題を回避するためには、適切なデータ構造を選択し、メモリの使用を最適化する必要があります。また、不要な参照を削除することも重要です。Goのプログラムでメモリリークが発生している場合は、プログラムを検討し、不要な参照や循環参照などを特定して修正する必要があります。
```

2024-02-15 03:26 UTC, kazuoikeda1411 commented on app/model/equipment.go
> +	}
いい感じだと思う！

2024-02-15 03:27 UTC, kazuoikeda1411 commented
一点だけ検討して〜泣
https://github.com/tetsu-777/rakuraku-reserve-app/pull/35#discussion_r1489399808

2024-02-15 21:49 UTC, kazuoikeda1411 approved these changes
確認しました！
対応ありがとう〜
一点変更箇所あるけど修正したらマージして大丈夫です🙇

2024-02-15 21:49 UTC, kazuoikeda1411 commented on app/controller/equipment_controller.go
> +	validate := validator.New()
変数定義は使うところの近くがいいかな！
使用箇所（`err := validate.Struct(equipmentReservingRequest)`）の上部に変更お願いします🙇

2024-02-16 10:55 UTC, tetsu-777 commented on app/controller/equipment_controller.go
> +	validate := validator.New()
おｋ

2024-02-16 11:04 UTC, merged