機材予約を論理削除　API
tetsu-777/rakuraku-reserve-app pull request #38
Opened 2024-02-16 12:10 UTC by tetsu-777

# 機能詳細
- 機材予約を論理削除（delete_atカラムを更新する）
- DELETE　/api/equipments/:equipmentId/reserve/:reserveId
- 削除対象の条件として、equipmentId と　reserveId の合致し、且つ、deleted_atがnullのものとする。

# 実装確認
- 正常時　http://localhost:8080/api/equipments/1/reserve/1
<img width="866" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/131426881/c165f5be-0ac9-43d8-805d-468077222e39">

- 異常時（合致するレコードが無い）　http://localhost:8080/api/equipments/1/reserve/4
<img width="888" alt="image" src="https://github.com/tetsu-777/rakuraku-reserve-app/assets/131426881/7920650a-9186-4f16-b433-2544757bc379">

# 共有事項
- 特になし

2024-02-16 13:42 UTC, Rin0107 requested changes
実装LGTM！
一点だけ修正お願い！

2024-02-16 13:42 UTC, Rin0107 commented on app/controller/equipment_controller.go
> +		c.IndentedJSON(200, gin.H{"message": "Reserved equipment successfully"})
【修正依頼】
メッセージに違和感あり！
「正常に予約できた」みたいになってる！

2024-02-20 09:09 UTC, tetsu-777 commented on app/controller/equipment_controller.go
> +		c.IndentedJSON(200, gin.H{"message": "Reserved equipment successfully"})
errがnullの時だったから、そうしてたけど、if err != nil の方が統一感あるから修正しておきました！

2024-02-22 13:37 UTC, Rin0107 commented on app/controller/equipment_controller.go
> +		c.IndentedJSON(200, gin.H{"message": "Reserved equipment successfully"})
あ、そゆことか！笑

2024-02-22 13:37 UTC, Rin0107 approved these changes

2024-02-22 13:37 UTC, Rin0107 commented
LGTM!

2024-02-27 09:41 UTC, merged