ユーザーの予約情報一覧を取得
tetsu-777/rakuraku-reserve-app pull request #43
Opened 2024-02-18 03:26 UTC by kariyana

# 機能詳細
-  ユーザーIDで指定したユーザーに関する予約情報を取得する。（予約の終了時が現在の時刻を過ぎていないものだけ）

# 実装確認
-  正常型 http://localhost:8080/api/equipments/reserve/1 (ユーザーID1のみの予約一覧)
![スクリーンショット 2024-02-18 122048](https://github.com/tetsu-777/rakuraku-reserve-app/assets/141194107/a925bfe3-e21b-499e-8bbc-b60bdbd8ee6b)

- 異常系　http://localhost:8080/api/equipments/reserve/5 (予約が一件もない場合)
![スクリーンショット 2024-02-18 122115](https://github.com/tetsu-777/rakuraku-reserve-app/assets/141194107/75a36742-1410-4d5f-bec0-efd5cb2d843d)

- 異常系　http://localhost:8080/api/equipments/reserve/1a (文字列が入力された場合)
![スクリーンショット 2024-02-18 122105](https://github.com/tetsu-777/rakuraku-reserve-app/assets/141194107/8a05afce-372f-4de7-817e-b84600f225ba)

# 共有事項

2024-02-18 12:00 UTC, Rin0107 requested changes
【修正・全体との共有依頼】

修正一点と、開発メンバーで考えて話し合って見てほしいのが一点！

2024-02-18 12:00 UTC, Rin0107 commented on app/model/equipment.go
> +// type EquipmentReservation struct {
【修正依頼】

使わないなら削除よろしく！

2024-03-17 03:08 UTC, kariyana commented on app/model/equipment.go
> +// type EquipmentReservation struct {
OK

2024-03-17 03:12 UTC, kariyana commented on app/model/equipment_reservation.go
> +	EquipmentId int `json:"equipmentId,omitempty"`
## リレーション先の情報も取得できるようにしました。

- ユーザーに紐づく予約情報一覧
http://localhost:8080/api/equipments/reserve/1
![スクリーンショット 2024-03-17 120638](https://github.com/tetsu-777/rakuraku-reserve-app/assets/141194107/00754d67-9b14-4ef5-91d1-ef342edb07e5)
- 機材に紐づく予約情報一覧
http://localhost:8080/api/equipments/2/reserve
![スクリーンショット 2024-03-17 120647](https://github.com/tetsu-777/rakuraku-reserve-app/assets/141194107/4451314e-a2c9-4146-913d-4b0bde9381f5)

2024-03-17 04:04 UTC, Rin0107 commented
このブランチpullしてdocker compose up -dしたら添付のエラーが出てたちあげれんかった！
確認よろしく！

![image](https://github.com/tetsu-777/rakuraku-reserve-app/assets/103812696/31932846-73f3-4cac-b13d-01ce5a21c721)

2024-03-17 04:18 UTC, kariyana commented
model/equipmentファイルにてtimeのimportを削除してしまっていたので、再度追加しました。確認のほどお願いいたします。

2024-03-17 05:11 UTC, Rin0107 commented on app/model/equipment_reservation.go
> +	EquipmentId int `json:"equipmentId,omitempty"`
LGTM!

2024-03-17 05:11 UTC, Rin0107 commented
LGTM!

2024-03-17 05:11 UTC, Rin0107 approved these changes

2024-03-17 05:14 UTC, merged